### ISSUE TITLE
Issue on running plan and locating plan

### ISSUE THREAD

**Issue by mortizTAG** [liatrio/terraform-change-pr-commenter#15]
Hi 

I have the following setup on GA
```
   - name: terraform-plan
      id: plan
      if: github.event_name == 'pull_request'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ MY_REGION }}
      run: |
        terraform init
        terraform workspace select dev
        terraform plan -out=tfplan.plan
        terraform show -no-color -json tfplan.plan > my-tfplan.json
        pwd
        ls -lh

    - name: Terraform Change PR Commenter
      # You may pin to the exact commit or the version.
      # uses: liatrio/terraform-change-pr-commenter@6557e8192d5a364386b91f60d1e375722e408839
      uses: liatrio/terraform-change-pr-commenter@v1.0.2
      with:
        # File location for the Terraform Plan JSON file
        json-file: terraform/cluster/my-tfplan.json
        # GitHub Token
        #github-token: # optional, default is ${{github.token}}
```

When using Terraform Change PR Commenter on json-file i have tried:
a- json-file: terraform/cluster/my-tfplan.json
b- json-file: my-tfplan.json

Results
a- 
```
Run liatrio/terraform-change-pr-commenter@v1.0.[2]
  with:
    json-file: terraform/cluster/everest-tfplan.json
    github-token: ***
  env:
    TERRAFORM_CLI_PATH: /home/runner/work/_temp/ddd218ff-d74d-4746-aa8a-758bdd[3]
Found PR # 939 from workflow context - proceeding to comment.
Error: Unexpected token c in JSON at position 1
```
b-
```
Run liatrio/terraform-change-pr-commenter@v1.0.2
Found PR # 939 from workflow context - proceeding to comment.
Error: ENOENT: no such file or directory, open 'tfplan.json'
```

Any ideas what am i missing?

**Comment by RobertKelly** [comment]
Hello there.  This is usually just the file location.  Looks like you create the file `my-tfplan.json` in the default location with `terraform show`.  If Terraform can run without any path change and the `terraform show` command works, you may just be able to set `json-file: my-tfplan.json`.

**Comment by RobertKelly** [comment]
Looking again, your first `a` scenario may be getting a file but is it proper JSON?  Can you cat/print and see if it's a good plan JSON file?

**Comment by mortizTAG** [comment]
Thanks for reply @RobertKelly 
Yes it seems json is valid, I did the plan locally as well format the output with jq etc.
On the a  scenario --- i am doing ls -lh just to get sure file is there etc ... File is there but it is almost 5MB .. could exists a restriction on size?

`-rw-r--r-- 1 runner docker 5.7M Mar 22 23:57 my-tfplan.json`

Thanks

**Comment by RobertKelly** [comment]
I am curious if that's the issue.  Can you potentially share this file?  We may be able to reproduce.  I haven't been able to reproduce it otherwise.  Can you try with a smaller subset of resources?

**Comment by w0rldart** [comment]
Hello there. I experience the same issue at the moment 

`Error: Unexpected token c in JSON at position 1`

I do have a quite small set of changes and I have validated the json file (no problem there)
This is my playbook

```
    steps:
      - uses: actions/checkout@v3
     
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        run: terraform init
        working-directory: "./terraform/"

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: "./terraform/"

      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: "./terraform/"

      - name: Terraform plan
        run: terraform plan -out tfplan.plan
        working-directory: "./terraform/"

      - name: Terraform show
        run: terraform show -no-color -json tfplan.plan > tfplan.json
        working-directory: "./terraform/"

      - name: Debug
        continue-on-error: true
        run: |
          pwd
          ls -al
          cat ./terraform/tfplan.json

      - name: Terraform Change PR Commenter
        uses: liatrio/terraform-change-pr-commenter@v1.3.2
        with:
          json-file: ./terraform/tfplan.json
          expand-comment: 'true' 
```

**Comment by RobertKelly** [comment]
> Hello there. I experience the same issue at the moment
> 
> `Error: Unexpected token c in JSON at position 1`
> 
> I do have a quite small set of changes and I have validated the json file (no problem there) This is my playbook
> 
> ```
>     steps:
>       - uses: actions/checkout@v3
>      
>       - uses: hashicorp/setup-terraform@v2
>         with:
>           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
> 
>       - name: Terraform init
>         run: terraform init
>         working-directory: "./terraform/"
> 
>       - name: Terraform Format
>         run: terraform fmt -check
>         working-directory: "./terraform/"
> 
>       - name: Terraform Validate
>         run: terraform validate -no-color
>         working-directory: "./terraform/"
> 
>       - name: Terraform plan
>         run: terraform plan -out tfplan.plan
>         working-directory: "./terraform/"
> 
>       - name: Terraform show
>         run: terraform show -no-color -json tfplan.plan > tfplan.json
>         working-directory: "./terraform/"
> 
>       - name: Debug
>         continue-on-error: true
>         run: |
>           pwd
>           ls -al
>           cat ./terraform/tfplan.json
> 
>       - name: Terraform Change PR Commenter
>         uses: liatrio/terraform-change-pr-commenter@v1.3.2
>         with:
>           json-file: ./terraform/tfplan.json
>           expand-comment: 'true' 
> ```



> Hello there. I experience the same issue at the moment
> 
> `Error: Unexpected token c in JSON at position 1`
> 
> I do have a quite small set of changes and I have validated the json file (no problem there) This is my playbook
> 
> ```
>     steps:
>       - uses: actions/checkout@v3
>      
>       - uses: hashicorp/setup-terraform@v2
>         with:
>           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
> 
>       - name: Terraform init
>         run: terraform init
>         working-directory: "./terraform/"
> 
>       - name: Terraform Format
>         run: terraform fmt -check
>         working-directory: "./terraform/"
> 
>       - name: Terraform Validate
>         run: terraform validate -no-color
>         working-directory: "./terraform/"
> 
>       - name: Terraform plan
>         run: terraform plan -out tfplan.plan
>         working-directory: "./terraform/"
> 
>       - name: Terraform show
>         run: terraform show -no-color -json tfplan.plan > tfplan.json
>         working-directory: "./terraform/"
> 
>       - name: Debug
>         continue-on-error: true
>         run: |
>           pwd
>           ls -al
>           cat ./terraform/tfplan.json
> 
>       - name: Terraform Change PR Commenter
>         uses: liatrio/terraform-change-pr-commenter@v1.3.2
>         with:
>           json-file: ./terraform/tfplan.json
>           expand-comment: 'true' 
> ```

I'll try to reproduce this one.  What is the size of the plan if you don't mind sharing?

**Comment by RobertKelly** [comment]
> Thank @RobertKelly for investigating this. Unfortunately, I don't have the size available to give to you anymore, but it was small. Maybe 2-3 resources changing, and 2 added. Something like that

Thank you for that info. It may be related to the workspace selection so I will still try to reproduce. If you can provide a json file or its contents for us to validate that would be a big help. We obviously wouldn't need any real resource info but any additional detail would be appreciated.

**Comment by w0rldart** [comment]
> > Thank @RobertKelly for investigating this. Unfortunately, I don't have the size available to give to you anymore, but it was small. Maybe 2-3 resources changing, and 2 added. Something like that
> 
> Thank you for that info. It may be related to the workspace selection so I will still try to reproduce. If you can provide a json file or its contents for us to validate that would be a big help. We obviously wouldn't need any real resource info but any additional detail would be appreciated.

I'd very much help with that, but I have no files to share anymore as I moved from this when the issue presented itself.

**Comment by JanMa** [comment]
Hey, I just ran into the same issue and found a solution for it.  If you make
use of the ` hashicorp/setup-terraform` action, you  need to ensure that the
[bundled wrapper script](https://github.com/hashicorp/setup-terraform#inputs) is not installed. It does not work properly when called
in a pipe and therefore the `tfplan.json` files we try to create do not contain
valid json.

The solution is to simply not install the wrapper script when using this action:
```yaml
       - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
```
