### ISSUE TITLE
expand comment by default

### ISSUE THREAD

**Issue by robert-spring** [liatrio/terraform-change-pr-commenter#16]
Any way have the pr comment expanded by default?

**Comment by RobertKelly** [comment]
Good question.  By default it's in a `<details>` block.  Maybe we can make this block optional.  Would that work for ya?

**Comment by RobertKelly** [comment]
Looks doable.  Looks like we can simply add an `open` attribute to the `<details>` tag.   
```
<details open>
<summary>This is an open details block</summary>
details, details, details
</details> 
```
<details open>
<summary>This is an open details block</summary>
details, details, details
</details> 

<details>
<summary>This is a closed details block</summary>
details, details, details
</details>

**Comment by RobertKelly** [comment]
> Any way have the pr comment expanded by default?

@robert-spring Give it a shot with the the latest v1.2.0 action and let me know how it goes.
```
uses: liatrio/terraform-change-pr-commenter@v1.2.0
with:
  json-file: my-tfplan.json
  expand-comment: 'true' 
```
