### ISSUE TITLE
Please support "working-directory"

### ISSUE THREAD

**Issue by ppuschmann** [liatrio/terraform-change-pr-commenter#45]
The action as of now does not support a default `working-directory`.

```yaml
jobs:
  terraform:
    name: 'Some Terraform-foo'
    defaults:
      run:
        working-directory: tf/my-resource-dir
```

The actual job has to get configured like this:

```yaml
      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -input=false -no-color -out=tfplan.plan && terraform show -no-color -json tfplan.plan > tfplan.json
        continue-on-error: true

      - name: Terraform Plan Commenter
        id: plan-commenter
        if: github.event_name == 'pull_request'
        uses: liatrio/terraform-change-pr-commenter@0e2fb6dce4278be1347e15144a807818c7e6eadb
        with:
          json-file: tf/my-resource-dir/tfplan.json
          expand-comment: 'true'
```

Please support the `working-directory`.
