### ISSUE TITLE
Update existing comment in place

### ISSUE THREAD

**Issue by cdata** [liatrio/terraform-change-pr-commenter#57]
Hey, I love this thing! It's just what I needed.

It would be nice if the action updated the comment in place as actions are re-run for a given PR (maybe as a configurable option). Historical comments are a little interesting but mostly just noisy.

**Comment by someshkoli** [comment]
hey @cdata, you can do something like below. This will hide previous comments and give you a clean view. Updating existing comment is not the best idea as your commit and comment may get out of sync.

PS: ive been running a fork of this action with some added features.

```yaml
      - uses: int128/hide-comment-action@v1
        with:
          contains: |
            Terraform Plan Summary: <b>${{ env.STACK }}</b>

      - uses: liatrio/terraform-change-pr-commenter@main
        with:
          json-file: tfplan.json
          expand-comment: "true"
          include-plan-job-summary: "true"
```

**Comment by jburns24** [comment]
@cdata We have added a feature to [v1.6.0](https://github.com/liatrio/terraform-change-pr-commenter/releases/tag/v1.6.0) that will hide all previous comments made by this action to reduce the noise.

```yaml
      - uses: liatrio/terraform-change-pr-commenter@v1.6.0
        with:
          json-file: envs/dev/plan.json
          hide-previous-comments: "true"
```

Which will result in a history like this

![image](https://github.com/user-attachments/assets/843275e0-4554-4ec4-b568-8f4b970af243)

In testing I did notice that I had to refresh the tab for the minimize to take effect FYI.
