### ISSUE TITLE
Hide previous comments hides all but last comment

### ISSUE THREAD

**Issue by ivantomica** [liatrio/terraform-change-pr-commenter#71]
First of all, I would like to thank you for the amazing, and almost feature complete action. I'm actively using it and find it very helpful.

I have one minor issue with the action when using it in combination with multiple environments and PRs. 

I would like to basically either:
- Update the existing comment in-place, selecting it by some unique identifier (like [borchero/terraform-plan-comment](https://github.com/borchero/terraform-plan-comment) action does)
- Fold only comments that match latest comment identifier prefix

Reason for this is the fact I'm using matrix strategy for Terraform Plan jobs, and during some runs I can get plan outputs for multiple Github Actions Environments, so the current behavior of the `hide-previous-comments` (as discussed in #57) doesn't suit me well since it hides all previous comments except the last submitted one, which means that all latest plan outputs are hidden but one (whichever completes last).

**Comment by RobertKelly** [comment]
Thanks @ivantomica - We'll review and try to understand the issue. We'll see what we can do.

**Comment by baolsen** [comment]
@RobertKelly we are also using this action with a matrix to run over several environments and running into this issue.

To give some idea what this looks like in a workflow:
```
jobs:
  generate_accounts_matrix:
    name: generate-accounts-matrix
    runs-on: ubuntu-latest
    outputs:
      accounts: ${{ steps.set-matrix.outputs.accounts }}
    steps:
      - uses: actions/checkout@v4
      - name: generate-accounts-matrix
        id: set-matrix
        run: |
          # Some scripting here to get a list of AWS accounts
          echo "accounts=$ACCOUNTS" >> "$GITHUB_OUTPUT"
```

Then we use it like so:
```
terraform-plan:
    needs: [generate_accounts_matrix]
    name: 🚀 Terraform Plan
    strategy:
      matrix:
        accounts: ${{ fromJSON(needs.generate_accounts_matrix.outputs.accounts) }}
    # runs-on: ubuntu-latest
    runs-on: codebuild-stuff-${{ matrix.accounts }}-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Version Check
        run: terraform --version
      - name: Terraform Init
        run: |
          tf_path=$(ls ./profiles | grep -e '${{ matrix.accounts }}')
          terraform init -reconfigure -backend-config=${tf_path}/terraform/this.terraform.tfbackend
      - name: Terraform Plan
        run: |
          tf_path=$(ls ./profiles | grep -e '${{ matrix.accounts }}')
          terraform plan -out=tfplan.plan  -var-file=${tf_path}/terraform/this.auto.tfvars
          terraform show -json tfplan.plan | jq . > tfplan.json
      - name: Terraform Change PR Commenter
        uses: liatrio/terraform-change-pr-commenter@v1.7.0
        with:
          json-file: ./tfplan.json
          expand-comment: true
          include-plan-job-summary: true
          comment-header: "Terraform Plan for ${{ matrix.accounts }}"
          # hide-previous-comments: true # This does not work when running a matrix strategy where multiple comments are left on one run
```

What I'm trying as a workaround is to see if I can use GitHub CLI to delete all the comments prior to the run. But it would be nicer if there was a method built into this action so we don't need to fiddle with GH CLI.
(If it works I'll paste an update here) 

A better option would be if we were able call the action once just to clear/hide all of its comments, as a preceding step.
That might be a simple workaround to implement, than trying to match up which comments relate to which runs etc.

Something like this:
```
terraform-clear-comments:
    needs: [generate_accounts_matrix]
    uses: liatrio/terraform-change-pr-commenter@v1.7.0
        with:
          hide_all_comments: true
    
terraform-plan:
    needs: [terraform_clear_comments]
```
