### ISSUE TITLE
feat: Include a link to the workflow run job that creates a comment.

### ISSUE THREAD

**Issue by danielewood** [liatrio/terraform-change-pr-commenter#84]
## Description

**As a** *DevOps Engineer*

**I would like** to have a link to the job which creates a comment in the PR.

**So that** instead of being sent to the Workflow Run, I am sent to the job. This would be incredibly useful for matrix jobs or when multiple jobs are triggered through a reusable workflow.

```yaml
  include-job-link:
    description: If true, include a link to the job run in the comment
    required: false
    default: false
```

## Acceptance Criteria

- [ ] New bool for including a link to the job run.
