### ISSUE TITLE
Filename instead of title

### ISSUE THREAD

**Issue by FrankGNL** [liatrio/terraform-change-pr-commenter#90]
## Description
If i understood the .js file correctly. If i use multiline json file by 'json-file' it will display the json file name instead of the title. But somehow for me it displays the default header 'Terraform Plan Changes'.

This is my step:
```
- name: Reporting
        uses: liatrio/terraform-change-pr-commenter@v1.11.0
        with:
          json-file: |
            ./environments/xxx/yyy/zzz/bbb/tfplan.json
            ./environments/xxx/yyy/aaa/ccc/tfplan.json
          expand-comment: 'true'
          quiet: 'true'
          include-plan-job-summary: 'true'
          hide-previous-comments: 'true'
```

Output from Action:
```
hidePreviousComments true
hidePreviousComments && context.eventName === pull_request true
Hiding previous comments.
includePlanSummary true
Adding plan output to job summary
quietMode true
hasNoChanges false
quietMode && hasNoChanges false
Found PR # 00 from pull_request event - proceeding to comment.
Adding comment to PR
Comment: 
Terraform Plan Changes
<details open>
<summary>
<b>Terraform Plan: 0 to be created, 0 to be deleted, 0 to be updated, 2 to be replaced, 27 unchanged.</b>
</summary>
```

On the assets folder in this repo there is even a screenshot with file names:
![Terraform Plan Output](https://github.com/liatrio/terraform-change-pr-commenter/raw/main/assets/plan-output-job-summary.png)
